<a href="https://colab.research.google.com/github/Asrar-Ahammad/Data-Science/blob/main/word_embeding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.11.0


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
# Sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
# Initialize vocabulary size.Increase in size increases processing time. 
voc_size = 10000

# One-Hot representation

In [9]:
# To caputre index of 1 in one hot encoding. 
onehot_rep = [one_hot(words,voc_size) for words in sent]

In [10]:
# Prints index of 1.    
# like : the - 3405, glass - 2916, of - 4033, milk - 9607
# Index value change everytime we run a program. 
print(onehot_rep)

[[3405, 2916, 4033, 9607], [3405, 2916, 4033, 8388], [3405, 3580, 4033, 145], [5382, 3179, 6338, 4659, 4803], [5382, 3179, 6338, 4659, 5549], [5498, 3405, 211, 4033, 8623], [3928, 3975, 5484, 4659]]


# Word Embedding representaion

In [11]:
# Inorder to make all the sentences to have same number of words we use padding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
# Pre padding adding '0' at begining
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 3405 2916 4033 9607]
 [   0    0    0    0 3405 2916 4033 8388]
 [   0    0    0    0 3405 3580 4033  145]
 [   0    0    0 5382 3179 6338 4659 4803]
 [   0    0    0 5382 3179 6338 4659 5549]
 [   0    0    0 5498 3405  211 4033 8623]
 [   0    0    0    0 3928 3975 5484 4659]]


In [14]:
# Post padding adding '0' at ending
sent_length = 8
embedded_docs1 = pad_sequences(onehot_rep, padding = 'post', maxlen = sent_length)
print(embedded_docs1)

[[3405 2916 4033 9607    0    0    0    0]
 [3405 2916 4033 8388    0    0    0    0]
 [3405 3580 4033  145    0    0    0    0]
 [5382 3179 6338 4659 4803    0    0    0]
 [5382 3179 6338 4659 5549    0    0    0]
 [5498 3405  211 4033 8623    0    0    0]
 [3928 3975 5484 4659    0    0    0    0]]


In [15]:
# 10 fearure dimensions has been taken
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam', 'mse')

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
# Every vocabulary is represented with 10 dimensions
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 232ms/step


array([[-0.01477735,  0.04135181,  0.02419624,  0.04229797,  0.0062138 ,
        -0.02573182, -0.02692796,  0.0210801 ,  0.04042765,  0.00643679],
       [-0.01477735,  0.04135181,  0.02419624,  0.04229797,  0.0062138 ,
        -0.02573182, -0.02692796,  0.0210801 ,  0.04042765,  0.00643679],
       [-0.01477735,  0.04135181,  0.02419624,  0.04229797,  0.0062138 ,
        -0.02573182, -0.02692796,  0.0210801 ,  0.04042765,  0.00643679],
       [-0.01477735,  0.04135181,  0.02419624,  0.04229797,  0.0062138 ,
        -0.02573182, -0.02692796,  0.0210801 ,  0.04042765,  0.00643679],
       [-0.00800285,  0.04065922, -0.01134449,  0.03255297, -0.03035432,
        -0.03573256, -0.02258143,  0.02573497, -0.00901552,  0.04935518],
       [ 0.00604673, -0.04158705,  0.02039074,  0.03033752, -0.01302658,
        -0.03221427,  0.0018662 ,  0.01958585, -0.01947663,  0.01029327],
       [-0.01204539, -0.01383554,  0.01412475,  0.03048605,  0.042975  ,
        -0.04815954,  0.03025471, -0.04154196

In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 57ms/step


array([[[-1.47773512e-02,  4.13518064e-02,  2.41962411e-02,
          4.22979705e-02,  6.21379539e-03, -2.57318150e-02,
         -2.69279610e-02,  2.10801028e-02,  4.04276513e-02,
          6.43678755e-03],
        [-1.47773512e-02,  4.13518064e-02,  2.41962411e-02,
          4.22979705e-02,  6.21379539e-03, -2.57318150e-02,
         -2.69279610e-02,  2.10801028e-02,  4.04276513e-02,
          6.43678755e-03],
        [-1.47773512e-02,  4.13518064e-02,  2.41962411e-02,
          4.22979705e-02,  6.21379539e-03, -2.57318150e-02,
         -2.69279610e-02,  2.10801028e-02,  4.04276513e-02,
          6.43678755e-03],
        [-1.47773512e-02,  4.13518064e-02,  2.41962411e-02,
          4.22979705e-02,  6.21379539e-03, -2.57318150e-02,
         -2.69279610e-02,  2.10801028e-02,  4.04276513e-02,
          6.43678755e-03],
        [-8.00285488e-03,  4.06592153e-02, -1.13444924e-02,
          3.25529687e-02, -3.03543210e-02, -3.57325561e-02,
         -2.25814339e-02,  2.57349722e-02, -9.015522